import { useEffect, useState } from 'react';
import { fetchPaper, fetchPaperSummary } from '../api';
import type { PaperDetail, PaperRef, PaperSummary } from '../types';

const CARD_LABELS: { key: keyof NonNullable<PaperSummary['cards']>; label: string }[] = [
  { key: 'problem', label: 'The problem' },
  { key: 'achieved', label: 'What they did' },
  { key: 'showed', label: 'What they showed' },
  { key: 'limitations', label: "What they didn't show" },
  { key: 'future', label: 'Future directions' },
];

const INTENT_LABEL: Record<string, string> = {
  background: 'background',
  methodology: 'method',
  method: 'method',
  result: 'result',
  results: 'result',
};

function paperLink(p: { doi: string | null; openAccessUrl: string | null; id: string }): string {
  if (p.doi) return p.doi.startsWith('http') ? p.doi : `https://doi.org/${p.doi}`;
  return p.openAccessUrl ?? `https://openalex.org/${p.id}`;
}

/** The 5 LLM summary cards, loaded lazily. Hidden entirely when summaries are disabled. */
function SummaryCards({ id, enabled }: { id: string; enabled: boolean }) {
  const [summary, setSummary] = useState<PaperSummary | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    if (!enabled) return;
    let live = true;
    setSummary(null);
    setError(false);
    fetchPaperSummary(id)
      .then((s) => live && setSummary(s))
      .catch(() => live && setError(true));
    return () => {
      live = false;
    };
  }, [id, enabled]);

  if (!enabled) return null;
  return (
    <section className="pv-summary">
      <h3 className="pv-h">In brief</h3>
      {!summary && !error && <p className="muted small">Summarising with the LLM…</p>}
      {error && <p className="muted small">Couldn&apos;t generate a summary.</p>}
      {summary?.noAbstract && (
        <p className="muted small">No abstract available for this paper, so no summary.</p>
      )}
      {summary?.error && <p className="muted small">Summary unavailable ({summary.error}).</p>}
      {summary?.cards && (
        <div className="pv-cards">
          {CARD_LABELS.map(({ key, label }) => (
            <div className="pv-card" key={key}>
              <div className="pv-card-label">{label}</div>
              <div className="pv-card-body">{summary.cards![key]}</div>
            </div>
          ))}
        </div>
      )}
      {summary?.cards &&
        (summary.mock ? (
          <p className="muted xsmall">Placeholder summary (prototype) — enable the API for real ones.</p>
        ) : (
          summary.model && (
            <p className="muted xsmall">Generated by {summary.model} from the abstract.</p>
          )
        ))}
    </section>
  );
}

/** One reference on the timeline: metadata + how the focal paper cites it. */
function TimelineRef({ r, onOpen }: { r: PaperRef; onOpen: (id: string) => void }) {
  return (
    <li className="tl-item">
      <div className="tl-year">{r.year ?? '—'}</div>
      <div className="tl-dot" />
      <div className="tl-body">
        <button className="tl-title linklike" onClick={() => onOpen(r.id)}>
          {r.title}
        </button>
        {r.inLibrary && <span className="tl-lib">in your library</span>}
        <div className="tl-meta">
          {r.authors[0] ?? '?'}
          {r.authors.length > 1 ? ' et al.' : ''} · {r.citedBy.toLocaleString()} citations
          {r.venue ? ` · ${r.venue}` : ''}
          {' · '}
          <a href={paperLink(r)} target="_blank" rel="noreferrer">
            open
          </a>
        </div>
        {(r.intents.length > 0 || r.contexts.length > 0) && (
          <div className="tl-ctx">
            {r.intents.length > 0 && (
              <div className="tl-intents">
                {[...new Set(r.intents.map((i) => INTENT_LABEL[i] ?? i))].map((i) => (
                  <span key={i} className={`intent intent-${i}`}>
                    {i}
                  </span>
                ))}
              </div>
            )}
            {r.contexts.slice(0, 2).map((c, i) => (
              <blockquote key={i} className="tl-quote">
                “{c}”
              </blockquote>
            ))}
          </div>
        )}
      </div>
    </li>
  );
}

interface Props {
  id: string;
  summariesEnabled: boolean;
  onOpen: (id: string) => void;
}

/** Full detail for one paper: header, LLM summary, and its references as a vertical timeline. */
export default function PaperView({ id, summariesEnabled, onOpen }: Props) {
  const [paper, setPaper] = useState<PaperDetail | null>(null);
  const [state, setState] = useState<'loading' | 'ok' | 'rate' | 'error'>('loading');

  useEffect(() => {
    let live = true;
    setPaper(null);
    setState('loading');
    fetchPaper(id)
      .then((r) => {
        if (!live) return;
        if (r.rateLimited) setState('rate');
        else if (r.paper) {
          setPaper(r.paper);
          setState('ok');
        } else setState('error');
      })
      .catch(() => live && setState('error'));
    return () => {
      live = false;
    };
  }, [id]);

  if (state === 'loading') return <div className="pv-loading muted">Loading paper…</div>;
  if (state === 'rate')
    return (
      <div className="pv-loading muted">
        OpenAlex daily limit reached — try again after the midnight-UTC reset.
      </div>
    );
  if (state === 'error' || !paper)
    return <div className="pv-loading muted">Could not load this paper.</div>;

  return (
    <article className="paper-view">
      <header className="pv-head">
        <h2 className="pv-title">{paper.title}</h2>
        <p className="pv-byline">
          {paper.authors.slice(0, 8).join(', ')}
          {paper.authors.length > 8 ? ' et al.' : ''}
        </p>
        <p className="pv-meta">
          {paper.year ?? '—'}
          {paper.venue ? ` · ${paper.venue}` : ''} · {paper.citedBy.toLocaleString()} citations
          {paper.topic ? ` · ${paper.topic}` : ''}
        </p>
        <div className="pv-links">
          <a href={paperLink(paper)} target="_blank" rel="noreferrer">
            {paper.doi ? 'DOI' : paper.openAccessUrl ? 'Open access PDF' : 'OpenAlex'}
          </a>
          <a href={`https://openalex.org/${paper.id}`} target="_blank" rel="noreferrer">
            OpenAlex
          </a>
        </div>
      </header>

      <SummaryCards id={paper.id} enabled={summariesEnabled} />

      {paper.abstract && (
        <details className="pv-abstract">
          <summary>Abstract</summary>
          <p>{paper.abstract}</p>
        </details>
      )}

      <section className="pv-refs">
        <h3 className="pv-h">
          Cited in this paper <span className="pv-count">{paper.references.length}</span>
        </h3>
        <p className="muted small">
          Every work this paper builds on, oldest first.
          {paper.contextsAvailable
            ? ' Quotes show how it is cited (via Semantic Scholar).'
            : ' Citation sentences weren’t available for this paper.'}
        </p>
        {paper.references.length === 0 ? (
          <p className="muted small">OpenAlex has no reference list for this work.</p>
        ) : (
          <ol className="timeline">
            {paper.references.map((r) => (
              <TimelineRef key={r.id} r={r} onOpen={onOpen} />
            ))}
          </ol>
        )}
      </section>
    </article>
  );
}
